In [ ]:
"""
latents = latents * self.scheduler.init_noise_sigma
        self.scheduler.set_timesteps(num_inference_steps, device=device)
        timesteps = self.scheduler.timesteps
latent_model_input = self.scheduler.scale_model_input(latent_model_input, t)

                # compute the previous noisy sample x_t -> x_t-1
                latents = self.scheduler.step(noise_pred, t, latents, **extra_step_kwargs).prev_sample
"""

In [ ]:
"""
# during training
            timesteps = torch.randint(0, noise_scheduler.config.num_train_timesteps, (bsz,), device=latents.device)
            timesteps = timesteps.long()
            
            # Add noise to the latents according to the noise magnitude at each timestep
            # (this is the forward diffusion process)
            noisy_latents = noise_scheduler.add_noise(latents, noise, timesteps)
"""

In [1]:
from diffusers import DDIMScheduler, LMSDiscreteScheduler

In [2]:
?DDIMScheduler

Init signature:
DDIMScheduler(
    num_train_timesteps: int = 1000,
    beta_start: float = 0.0001,
    beta_end: float = 0.02,
    beta_schedule: str = 'linear',
    trained_betas: Union[numpy.ndarray, List[float], NoneType] = None,
    clip_sample: bool = True,
    set_alpha_to_one: bool = True,
    steps_offset: int = 0,
    prediction_type: str = 'epsilon',
    **kwargs,
)
Docstring:     
Denoising diffusion implicit models is a scheduler that extends the denoising procedure introduced in denoising
diffusion probabilistic models (DDPMs) with non-Markovian guidance.

[`~ConfigMixin`] takes care of storing all config attributes that are passed in the scheduler's `__init__`
function, such as `num_train_timesteps`. They can be accessed via `scheduler.config.num_train_timesteps`.
[`SchedulerMixin`] provides general loading and saving functionality via the [`SchedulerMixin.save_pretrained`] and
[`~SchedulerMixin.from_pretrained`] functions.

For more details, see the original paper: http

In [5]:
ddim = DDIMScheduler(num_train_timesteps=1000,
                    beta_start=0.00085,
                    beta_end=0.012,
                    beta_schedule="linear",
                    steps_offset=1,
                    clip_sample=False)

In [6]:
?LMSDiscreteScheduler

Init signature:
LMSDiscreteScheduler(
    num_train_timesteps: int = 1000,
    beta_start: float = 0.0001,
    beta_end: float = 0.02,
    beta_schedule: str = 'linear',
    trained_betas: Union[numpy.ndarray, List[float], NoneType] = None,
    prediction_type: str = 'epsilon',
)
Docstring:     
Linear Multistep Scheduler for discrete beta schedules. Based on the original k-diffusion implementation by
Katherine Crowson:
https://github.com/crowsonkb/k-diffusion/blob/481677d114f6ea445aa009cf5bd7a9cdee909e47/k_diffusion/sampling.py#L181

[`~ConfigMixin`] takes care of storing all config attributes that are passed in the scheduler's `__init__`
function, such as `num_train_timesteps`. They can be accessed via `scheduler.config.num_train_timesteps`.
[`SchedulerMixin`] provides general loading and saving functionality via the [`SchedulerMixin.save_pretrained`] and
[`~SchedulerMixin.from_pretrained`] functions.

Args:
    num_train_timesteps (`int`): number of diffusion steps used to train the

In [10]:
llms = LMSDiscreteScheduler(beta_start=0.00085, beta_end=0.012, beta_schedule="scaled_linear", num_train_timesteps=1000)

In [11]:
ddim.init_noise_sigma

1.0

In [12]:
llms.init_noise_sigma

tensor(14.6146)

In [13]:
?ddim.set_timesteps

Signature:
ddim.set_timesteps(
    num_inference_steps: int,
    device: Union[str, torch.device] = None,
)
Docstring:
Sets the discrete timesteps used for the diffusion chain. Supporting function to be run before inference.

Args:
    num_inference_steps (`int`):
        the number of diffusion steps used when generating samples with a pre-trained model.
File:      ~/anaconda3/envs/python311/lib/python3.11/site-packages/diffusers/schedulers/scheduling_ddim.py
Type:      method

In [14]:
?llms.set_timesteps

Signature:
llms.set_timesteps(
    num_inference_steps: int,
    device: Union[str, torch.device] = None,
)
Docstring:
Sets the timesteps used for the diffusion chain. Supporting function to be run before inference.

Args:
    num_inference_steps (`int`):
        the number of diffusion steps used when generating samples with a pre-trained model.
    device (`str` or `torch.device`, optional):
        the device to which the timesteps should be moved to. If `None`, the timesteps are not moved.
File:      ~/anaconda3/envs/python311/lib/python3.11/site-packages/diffusers/schedulers/scheduling_lms_discrete.py
Type:      method

In [15]:
ddim.set_timesteps(50)
ddim.timesteps

tensor([981, 961, 941, 921, 901, 881, 861, 841, 821, 801, 781, 761, 741, 721,
        701, 681, 661, 641, 621, 601, 581, 561, 541, 521, 501, 481, 461, 441,
        421, 401, 381, 361, 341, 321, 301, 281, 261, 241, 221, 201, 181, 161,
        141, 121, 101,  81,  61,  41,  21,   1])

In [16]:
ddim.num_inference_steps

50

In [17]:
ddim.num_train_timesteps

1000

In [18]:
ddim.init_noise_sigma

1.0

In [19]:
?ddim.scale_model_input

Signature:
ddim.scale_model_input(
    sample: torch.FloatTensor,
    timestep: Optional[int] = None,
) -> torch.FloatTensor
Docstring:
Ensures interchangeability with schedulers that need to scale the denoising model input depending on the
current timestep.

Args:
    sample (`torch.FloatTensor`): input sample
    timestep (`int`, optional): current timestep

Returns:
    `torch.FloatTensor`: scaled input sample
File:      ~/anaconda3/envs/python311/lib/python3.11/site-packages/diffusers/schedulers/scheduling_ddim.py
Type:      method

In [21]:
llms.config.num_train_timesteps

1000

In [23]:
import torch
timesteps = torch.randint(0, 1000, (5, ))
timesteps

tensor([296, 109,  70, 262, 545])

In [24]:
?llms.add_noise

Signature:
llms.add_noise(
    original_samples: torch.FloatTensor,
    noise: torch.FloatTensor,
    timesteps: torch.FloatTensor,
) -> torch.FloatTensor
Docstring: <no docstring>
File:      ~/anaconda3/envs/python311/lib/python3.11/site-packages/diffusers/schedulers/scheduling_lms_discrete.py
Type:      method

In [25]:
latents = torch.randn(5, 4, 64, 64)
noise = torch.randn_like(latents)

In [26]:
timesteps = torch.randint(0, llms.config.num_train_timesteps, (5,))
timesteps = timesteps.long()

In [27]:
timesteps

tensor([712, 468, 464, 341, 657])

In [29]:
noisy_latents = llms.add_noise(latents, noise, timesteps)

In [33]:
llms.sigmas

tensor([14.6146, 14.5263, 14.4386,  ...,  0.0413,  0.0292,  0.0000])